version: '3.9'

volumes:
  cluster-file: {}

services:
  app:
    build: .
    platform: linux/amd64
    volumes:
      - cluster-file:/etc/foundationdb/
    depends_on:
      - foundationdb

  foundationdb:
    image: foundationdb/foundationdb:7.2.2
    environment:
      FDB_CLUSTER_FILE: /etc/foundationdb/fdb.cluster
    platform: linux/amd64
    volumes:
      - cluster-file:/etc/foundationdb/